### ISSUE TITLE
Index out of bounds in file-fact

### ISSUE THREAD

**Issue by jerger** [DomainDrivenArchitecture/dda-serverspec-crate#11]
10:10:47.890 [operate-12] ERROR pallet.action-plan - Exception in execute-action-map
java.lang.IndexOutOfBoundsException: null
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:153)
	at clojure.lang.PersistentVector.nth(PersistentVector.java:157)
	at clojure.lang.RT.nth(RT.java:839)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20106$clean_up_negative_find__20111$fn__20112.invoke(file.clj:55)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20106$clean_up_negative_find__20111.invoke(file.clj:51)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20129$parse_find_line__20134$fn__20135.invoke(file.clj:63)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20129$parse_find_line__20134.invoke(file.clj:58)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20152$create_line_parse_result__20157$fn__20158.invoke(file.clj:74)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$fn__20152$create_line_parse_result__20157.invoke(file.clj:73)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at dda.pallet.dda_serverspec_crate.infra.fact.file$parse_find.invoke(file.clj:80)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at dda.pallet.commons.fact$fn__19900$fact_result__19905$fn__19906.invoke(fact.clj:67)
	at dda.pallet.commons.fact$fn__19900$fact_result__19905.invoke(fact.clj:54)
	at dda.pallet.commons.fact$fn__19926$collect_fact__19931$fn__19932$action__4106__auto___direct__19937$clj_action19936__19938.invoke(fact.clj:100)
	at pallet.local.execute$clojure_on_origin.invoke(execute.clj:97)
	at pallet.executors$default_executor.invoke(executors.clj:62)
	at pallet.action_plan$execute_action_map.invoke(action_plan.clj:599)
	at pallet.action_plan$execute$exec_action__4040$execute_with_error_check__4041.invoke(action_plan.clj:672)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2070$m_bind_state__2075$fn__2076.invoke(monads.clj:341)
	at pallet.action_plan$map_action_f.invoke(action_plan.clj:541)
	at pallet.action_plan$execute.invoke(action_plan.clj:673)
	at pallet.core.api$execute_action_plan_STAR_.invoke(api.clj:179)
	at pallet.core.api$fn__11028.invoke(api.clj:199)
	at clojure.lang.MultiFn.invoke(MultiFn.java:271)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.core$partial$fn__4533.doInvoke(core.clj:2512)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at pallet.core.primitives$async_fsm$run_async__11154$async_fsm__11156.invoke(primitives.clj:42)
	at pallet.algo.fsmop$report_exceptions$report_exceptions__4483.invoke(fsmop.clj:64)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

cli:
find /root/.yarn -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/packer -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/aws -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /root/.npm -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/check-asg.sh -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/terraform -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/aws_get_prod_ci_role_session.sh -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /root/.gradle -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/aws_get_session -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/aws_get_session.sh -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/lib/dda-pallet/dda-serverspec.jar -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1; find /usr/local/bin/amicleaner -prune -printf "%p'%s'%u'%g'%m'%y'%l'%c'%t'%a\n" 2>&1;

result:
find: '/root/.yarn': No such file or directory
/usr/local/bin/packer'95984305'root'root'755'f''Tue Jun 26 09:50:45.7889129420 2018'Tue May 29 12:26:08.0000000000 2018'Tue May 29 12:26:08.0000000000 2018
/usr/local/bin/aws'814'root'root'755'f''Tue Jun 26 09:50:39.7689119130 2018'Tue Jun 26 09:46:54.0000000000 2018'Tue Jun 26 09:46:54.0000000000 2018
find: '/root/.npm': No such file or directory
/usr/local/bin/check-asg.sh'1954'root'root'775'f''Tue Jun 26 09:50:39.7809119150 2018'Tue Jun 26 09:28:05.0000000000 2018'Tue Jun 26 09:28:05.0000000000 2018
/usr/local/bin/terraform'69122624'root'root'775'f''Tue Jun 26 09:50:50.0969136750 2018'Tue Apr 10 16:52:30.0000000000 2018'Tue Apr 10 16:52:30.0000000000 2018
/usr/local/bin/aws_get_prod_ci_role_session.sh'784'root'root'775'f''Tue Jun 26 09:50:39.7689119130 2018'Tue Jun 26 09:28:05.0000000000 2018'Tue Jun 26 09:28:05.0000000000 2018
/root/.gradle'4096'root'root'755'd''Tue Jun 26 09:52:02.5569255210 2018'Tue Jun 26 09:42:33.0000000000 2018'Tue Jun 26 09:52:02.6729255390 2018
/usr/local/bin/aws_get_session'33'root'root'777'l'/usr/local/bin/aws_get_session.sh'Tue Jun 26 09:50:39.7689119130 2018'Tue Jun 26 09:47:32.0000000000 2018'Tue Jun 26 09:47:32.0000000000 2018
/usr/local/bin/aws_get_session.sh'2312'root'root'775'f''Tue Jun 26 09:50:39.7689119130 2018'Tue Jun 26 09:28:05.0000000000 2018'Tue Jun 26 09:28:05.0000000000 2018
/usr/local/lib/dda-pallet/dda-serverspec.jar'35610432'root'root'644'f''Tue Jun 26 09:50:52.2889140470 2018'Tue Jun 26 09:41:10.0000000000 2018'Tue Jun 26 09:41:10.0000000000 2018
/usr/local/bin/amicleaner'215'root'root'755'f''Tue Jun 26 09:50:39.7609119120 2018'Tue Jun 26 09:48:46.0000000000 2018'Tue Jun 26 09:48:46.0000000000 2018

**Comment by jerger** [comment]
Fixed with https://github.com/DomainDrivenArchitecture/dda-serverspec-crate/commit/01738f5678e72514ea981b010bbff337911039bc
