### ISSUE TITLE
netcat issue on localhost

### ISSUE THREAD

**Issue by jerger** [DomainDrivenArchitecture/dda-serverspec-crate#9]
15:12:11.736 [operate-9] ERROR pallet.action-plan - Exception in execute-action-map
java.lang.IndexOutOfBoundsException: null
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:153)
	at clojure.lang.PersistentVector.nth(PersistentVector.java:157)
	at clojure.lang.RT.nth(RT.java:839)
	at dda.pallet.dda_serverspec_crate.infra.fact.netcat$fn__20304$parse_result__20309$fn__20310.invoke(netcat.clj:64)
	at dda.pallet.dda_serverspec_crate.infra.fact.netcat$fn__20304$parse_result__20309.invoke(netcat.clj:62)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at dda.pallet.dda_serverspec_crate.infra.fact.netcat$parse_netcat.invoke(netcat.clj:72)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at dda.pallet.commons.fact$fn__19904$fact_result__19909$fn__19910.invoke(fact.clj:67)
	at dda.pallet.commons.fact$fn__19904$fact_result__19909.invoke(fact.clj:54)
	at dda.pallet.commons.fact$fn__19930$collect_fact__19935$fn__19936$action__5493__auto___direct__19941$clj_action19940__19942.invoke(fact.clj:100)
	at pallet.local.execute$clojure_on_origin.invoke(execute.clj:97)
	at pallet.executors$default_executor.invoke(executors.clj:62)
	at pallet.action_plan$execute_action_map.invoke(action_plan.clj:599)
	at pallet.action_plan$execute$exec_action__5427$execute_with_error_check__5428.invoke(action_plan.clj:672)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:341)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:340)
	at clojure.algo.monads$fn__2772$m_bind_state__2777$fn__2778.invoke(monads.clj:341)
	at pallet.action_plan$map_action_f.invoke(action_plan.clj:541)
	at pallet.action_plan$execute.invoke(action_plan.clj:673)
	at pallet.core.api$execute_action_plan_STAR_.invoke(api.clj:179)
	at pallet.core.api$fn__11028.invoke(api.clj:199)
	at clojure.lang.MultiFn.invoke(MultiFn.java:271)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.core$partial$fn__4533.doInvoke(core.clj:2512)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at pallet.core.primitives$async_fsm$run_async__11154$async_fsm__11156.invoke(primitives.clj:42)
	at pallet.algo.fsmop$report_exceptions$report_exceptions__3330.invoke(fsmop.clj:64)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jerger** [comment]
fact input is: `172.24.26.155_22_8,SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4`
